mybatis-plus:
  type-aliases-package: com.ibase.domain
  mapper-locations: classpath:/mapper/**/*.xml

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://101.43.166.59:30336/sm?useUnicode=true&characterEncoding=utf8&useSSL=false&autoReconnect=true&serverTimezone=UTC
    username: root
    password: 3344520..hhy
    hikari:
      # 是允许连接在连接池中空闲的最长时间
      minimum-idle: 5
      # 是允许连接在连接池中空闲的最长时间（以毫秒为单位）
      idle-timeout: 600000
      # 配置最大池大小
      maximum-pool-size: 10
      # 配置从池返回的连接的默认自动提交行为。默认值为true
      auto-commit: true
      # 连接池的名称
      pool-name: MyHikariCP
      # 池中连接关闭后的最长生命周期（以毫秒为单位）
      max-lifetime: 1800000
      # 是客户端等待连接池连接的最大毫秒数
      connection-timeout: 30000
      # 开启连接监测泄露
      leak-detection-threshold: 5000
      # 测试连接数据库
      connection-test-query: SELECT 1
